"""add users and ownership

Revision ID: 31b456694013
Revises: 
Create Date: 2025-12-23 16:48:43.370495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b456694013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            'fk_chat_session_user_id_user',
            'user',
            ['user_id'],
            ['id']
        )

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            'fk_message_user_id_user',
            'user',
            ['user_id'],
            ['id']
        )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_session_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###

