"""add allowed_departments to user

Revision ID: e0e58b03301b
Revises: 7c9d2e1f4a7b
Create Date: 2026-06-18 13:14:11.597506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e58b03301b'
down_revision = '7c9d2e1f4a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_departments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('allowed_departments')

    # ### end Alembic commands ###
