# app/rag_logic/agent_intermedios.py

from __future__ import annotations

from typing import Any, Dict, List, Tuple, Union, Optional

from langchain_openai import ChatOpenAI
from langchain.schema import SystemMessage, HumanMessage

from .tools import ChatWithDocumentTool, SummarizeDocumentTool
from .sql_tool import SQLDatabaseTool
from .excel_tool import ExcelAnalysisTool
from .web_search import WebSearchTool

from langchain_core.callbacks import CallbackManager

ChatHistory = List[Tuple[str, str]]
AgentResult = Dict[str, Any]


def _normalize_result(raw: Union[str, AgentResult]) -> AgentResult:
    """
    Normaliza la salida de cualquier herramienta a un dict con:
    - answer: str
    - source_documents: list
    """
    if isinstance(raw, str):
        return {"answer": raw, "source_documents": []}
    if "answer" not in raw:
        raw["answer"] = ""
    if "source_documents" not in raw:
        raw["source_documents"] = []
    return raw


def _build_context_from_docs(docs: List[Any], max_docs: int = 8, max_chars: int = 2000) -> str:
    """
    Construye un bloque de contexto legible a partir de los source_documents.
    Admite tanto Document de LangChain como dicts serializados.
    """
    if not docs:
        return ""

    chunks = []
    for d in docs[:max_docs]:
        if hasattr(d, "page_content"):
            text = getattr(d, "page_content", "") or ""
            meta = getattr(d, "metadata", {}) or {}
        elif isinstance(d, dict):
            text = d.get("page_content", "") or ""
            meta = d.get("metadata", {}) or {}
        else:
            text, meta = "", {}

        text = text[:max_chars]
        fuente = meta.get("source") or meta.get("relative_path") or ""
        header = f"[Fuente: {fuente}]" if fuente else "[Fragmento sin nombre de archivo]"
        chunks.append(f"{header}\n{text}")

    return "\n\n---\n\n".join(chunks)


# ======================================================================
# DOCUMENT QA AGENT
# ======================================================================

class DocumentQAAgent:
    """
    Agente de preguntas/respuestas sobre documentos del vector store.
    - Usa ChatWithDocumentTool para recuperar contexto + respuesta preliminar.
    - Después pasa por un LLM con un prompt de "analista documental senior"
      para:
        * Verificar coherencia con el contexto.
        * Completar/limitar la respuesta.
                * Restate it clearly for a business user.
    """

    def __init__(
        self,
        tool: ChatWithDocumentTool,
        model_name: str = "gpt-4o-mini",
        temperature: float = 0.2,
        callbacks: Optional[list] = None,
    ) -> None:
        self.tool = tool
        self.name = tool.name
        self.callbacks = callbacks or []
        

        cb_manager = CallbackManager(self.callbacks) if self.callbacks else None
        self.llm = ChatOpenAI(model=model_name, temperature=temperature, callback_manager=cb_manager)


    def run(
        self,
        question: str,
        chat_history: ChatHistory,
        extra_documents: Optional[List[Any]] = None,
    ) -> AgentResult:

        # 1) Recuperación + respuesta preliminar
        raw = self.tool.run(
            {"question": question, "chat_history": chat_history},
            callbacks=self.callbacks,
        )

        result = _normalize_result(raw)

        # 2) Contexto textual a partir de los documentos
        docs = result.get("source_documents", [])

        # 🔹 Inyectar memoria conversacional como contexto adicional
        if extra_documents:
            docs = list(extra_documents) + list(docs)

        context_text = _build_context_from_docs(docs)


        # 3) Re-razonamiento con un rol claro
        system_prompt = (
            "You are a SENIOR HR DOCUMENT ANALYST.\n"
            "Your job is to answer the user's question ONLY using the information "
            "present in the provided context fragments.\n\n"
            "KEY RULES:\n"
            "- Always respond in clear, professional English.\n"
            "- Do not mention technical concepts like 'vector store', 'chunks', 'embeddings', etc.\n"
            "- If something is not in the context, say so explicitly (e.g., "
            "'this information does not appear explicitly in the reviewed documents').\n"
            "- Never invent figures, dates or conclusions not supported by the context.\n"
            "- If there are multiple related pieces of information, synthesise them clearly "
            "for a business user, not a technical audience.\n"
        )
        user_prompt = (
            f"User question:\n{question}\n\n"
            f"Preliminary answer generated by the system:\n{result.get('answer', '').strip()}\n\n"
            "Relevant context fragments (may include metadata and excerpts from PDFs/Excel):\n"
            f"{context_text}\n\n"
            "Task:\n"
            "- Review the preliminary answer in light of the context.\n"
            "- Correct, complete or qualify the answer if necessary.\n"
            "- If the information is incomplete or ambiguous, explain clearly what is missing.\n"
            "- Return a single, clear final answer for the user.\n"
        )
        refined = self.llm.invoke(
            [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)],
        )
        result["answer"] = refined.content.strip()
        return result


# ======================================================================
# SUMMARY AGENT
# ======================================================================

class SummaryAgent:
    def __init__(
        self,
        tool: SummarizeDocumentTool,
        model_name: str = "gpt-4o-mini",
        temperature: float = 0.2,
        callbacks: Optional[list] = None,
    ) -> None:
        self.tool = tool
        self.name = tool.name
        self.callbacks = callbacks or []
        self.llm = ChatOpenAI(model_name=model_name, temperature=temperature, callbacks=self.callbacks)

    def run(self) -> AgentResult:
        raw = self.tool.run({}, callbacks=self.callbacks)
        result = _normalize_result(raw)


        base_summary = result.get("answer", "").strip()

        system_prompt = (
            "You are a SENIOR CONSULTANT. You will receive a raw summary and must transform it into a "
            "DETAILED SUMMARY (not a short one) for a business user.\n"
            "Rules:\n"
            "- Clear, professional English.\n"
            "- Preserve and expand useful detail: figures, dates, percentages and comparisons where available.\n"
            "- Do not invent anything.\n"
            "- Do not cut content: the goal is for the user to fully understand the document.\n"
        )
        user_prompt = (
            "Raw summary generated by the system:\n"
            f"{base_summary}\n\n"
            "Rewrite and structure the content using this format:\n"
            "1) What it is about (3-6 bullet points)\n"
            "2) Main sections/topics (list)\n"
            "3) Key findings (10-20 bullet points)\n"
            "4) Relevant data/metrics (if present)\n"
            "5) Implications (5-10)\n"
            "6) Recommendations (6-12)\n"
            "If information is missing, state it explicitly.\n"
        )
        refined = self.llm.invoke(
            [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)],
        )
        result["answer"] = refined.content.strip()
        return result


# ======================================================================
# SQL AGENT
# ======================================================================

class SQLAgent:
    """
    Agente de consultas al Data Lake / Redshift.
    - SQLDatabaseTool ejecuta la query y devuelve un resultado (texto / tabla renderizada).
    - El LLM interpreta ese resultado en lenguaje de negocio: conclusiones, advertencias, etc.
    """

    def __init__(
        self,
        tool: SQLDatabaseTool,
        model_name: str = "gpt-4o",
        temperature: float = 0.2,
        callbacks: Optional[list] = None,
    ) -> None:
        self.tool = tool
        self.name = tool.name
        self.callbacks = callbacks or []
        self.llm = ChatOpenAI(model_name=model_name, temperature=temperature, callbacks=self.callbacks)

    def run(self, query: str) -> AgentResult:
        raw = self.tool.run({"query": query}, callbacks=self.callbacks)
        result = _normalize_result(raw)

        sql_output = (result.get("answer") or "").strip()

        # ✅ Guardamos SIEMPRE el resultado bruto completo para poder renderizarlo al final
        result["sql_raw_output"] = sql_output

        # (Opcional pero recomendable) evitamos meter tablas gigantes al LLM
        MAX_SQL_CHARS_FOR_LLM = 12000
        sql_output_for_llm = sql_output if len(sql_output) <= MAX_SQL_CHARS_FOR_LLM else (
            sql_output[:MAX_SQL_CHARS_FOR_LLM]
            + "\n... [resultado SQL recortado solo para el análisis del LLM]"
        )

        system_prompt = (
            "You are a DATA ANALYST with a business focus.\n"
            "You receive the result of an already-executed SQL query (may be in text or table format).\n"
            "Your task is to interpret that result for a NON-technical person.\n"
            "Do not invent data that is not in the output. If something cannot be determined, say so.\n"
            "\n"
            "IMPORTANT (visualisation):\n"
            "- Always end your response with a '📊 Recommended Charts' section.\n"
            "- Rule 1: if there is a time column (date/day/month/week), recommend a LINE chart.\n"
            "- Rule 2: if there is no time column and few categories (<= 10), recommend a BAR chart.\n"
            "- Rule 3: if there are many categories, recommend BARS with 'Top N' and specify the criterion.\n"
            "- For each chart specify: (1) type, (2) X axis, (3) Y axis/metric, (4) segmentation/series if applicable.\n"
            "- Do not invent columns: use only those present in the output.\n"
        )
        user_prompt = (
            f"Original query (summary, do not reprocess):\n{query}\n\n"
            f"Raw result returned by the SQL tool:\n{sql_output_for_llm}\n\n"
            "Task:\n"
            "- Explain what these results mean in plain language.\n"
            "- Highlight totals, comparisons and any obvious insights.\n"
            "- Indicate if context is missing (e.g., no historical data, no benchmark).\n"
            "- Avoid mentioning SQL code or internal database details.\n"
            "- If the number of rows does not cover the full period, state this explicitly.\n"
            "- Do not invent tables or values. Do not paste the full dataset.\n"
            "\n"
            "Also add at the end EXACTLY one section:\n"
            "📊 Recommended Charts:\n"
            "- (Chart 1) Type: ... | X: ... | Y: ... | Series/segment: ...\n"
            "- (Chart 2) Type: ... | X: ... | Y: ... | Series/segment: ... (if applicable)\n"
        )
        refined = self.llm.invoke(
            [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)],
        )

        # ✅ El answer será el insight, pero el dato completo queda en sql_raw_output
        result["answer"] = refined.content.strip()
        return result


# ======================================================================
# EXCEL AGENT
# ======================================================================

class ExcelAgent:
    """
    Agente de análisis de Excel (planes de medios, cierres, facturación, etc.).
    - ExcelAnalysisTool se encarga de leer el archivo y hacer el análisis base.
    - El LLM re-interpreta ese análisis y lo traduce a insights de negocio.
    """

    def __init__(
        self,
        tool: ExcelAnalysisTool,
        model_name: str = "gpt-4o-mini",
        temperature: float = 0.2,
        callbacks: Optional[list] = None,
    ) -> None:
        self.tool = tool
        self.name = tool.name
        self.callbacks = callbacks or []
        self.llm = ChatOpenAI(model_name=model_name, temperature=temperature, callbacks=self.callbacks)

    def run(self, query: str, file_name_hint: str = "") -> AgentResult:
        raw = self.tool.run(
            {"query": query, "file_name_hint": file_name_hint},
            callbacks=self.callbacks,
        )
        result = _normalize_result(raw)

        excel_output = (result.get("answer") or "").strip()

        system_prompt = (
            "You are an HR DATA ANALYST expert at reading Excel reports.\n"
            "You will receive the description/result of an Excel analysis (headcount, salaries, performance...).\n"
            "Your task is to translate it into:\n"
            "- What the data shows (departments, periods, levels, locations).\n"
            "- What volume/costs/headcount figures are involved.\n"
            "- What basic conclusions can be drawn.\n"
        )
        user_prompt = (
            f"Original user request:\n{query}\n\n"
            f"File hint / context (if any): {file_name_hint}\n\n"
            f"Raw output from the Excel analyser:\n{excel_output}\n\n"
            "Task:\n"
            "- Restate this result in clear language, without unnecessary jargon.\n"
            "- Highlight important data points (dates, locations, levels, key figures).\n"
            "- If the file appears incomplete or does not answer the question well, explain this.\n"
        )
        refined = self.llm.invoke(
            [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)],
        )
        result["answer"] = refined.content.strip()
        return result


# ======================================================================
# WEB SEARCH AGENT
# ======================================================================

class WebSearchAgent:
    """
    Agente de búsqueda en internet.
    - WebSearchTool hace la búsqueda y devuelve un texto base.
    - El LLM lo resume, limpia redundancias y advierte de limitaciones.
    """

    def __init__(
        self,
        tool: WebSearchTool,
        model_name: str = "gpt-4o-mini",
        temperature: float = 0.2,
        callbacks: Optional[list] = None,
    ) -> None:
        self.tool = tool
        self.name = tool.name
        self.callbacks = callbacks or []
        self.llm = ChatOpenAI(model_name=model_name, temperature=temperature, callbacks=self.callbacks)

    def run(self, query: str) -> AgentResult:
        raw = self.tool.run({"query": query}, callbacks=self.callbacks)
        result = _normalize_result(raw)

        web_output = (result.get("answer") or "").strip()

        system_prompt = (
            "You are an ASSISTANT that summarises internet search results.\n"
            "Provide a clear, concise and useful response in English.\n"
            "If the information appears contradictory or unreliable, flag this.\n"
        )
        user_prompt = (
            f"User query for the web:\n{query}\n\n"
            f"Raw result returned by the web search tool:\n{web_output}\n\n"
            "Task:\n"
            "- Summarise the information in 3-6 sentences.\n"
            "- Include key dates, figures or definitions if present.\n"
            "- Flag any relevant limitations (e.g., 'information may have changed').\n"
        )
        refined = self.llm.invoke(
            [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)],
        )
        result["answer"] = refined.content.strip()
        return result
